version: "3.7"

services:

  backend:
    container_name: backend
    build: ./backend
    working_dir: /app/backend
    volumes: 
      - ./backend:/app/backend
    environment: 
      POSTGRES_USER: tandat
      POSTGRES_PASSWORD: root_123456
      POSTGRES_DB: symphony
      POSTGRES_HOST: postgres
    command: npm run dev
    ports:
      - 5000:5000

  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   working_dir: /app/frontend
  #   volumes:
  #     - ./frontend:/app/frontend
  #   ports:
  #     - 8000:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  postgres:
    restart: always
    environment:
      POSTGRES_USER: tandat
      POSTGRES_PASSWORD: root_123456
      POSTGRES_DB: symphony
      POSTGRES_HOST: postgres
    container_name: postgres
    image: postgres
    ports:
      - 5433:5432
