version: "3.7"

services:

  postgres:
    restart: always
    environment:
      POSTGRES_USER: tandat
      POSTGRES_PASSWORD: root_123456
      POSTGRES_DB: symphony
      POSTGRES_HOST: postgres
    container_name: postgres
    image: postgres
    ports:
      - 5433:5432

  mongo:
    image: mongo
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tandat
      MONGO_INITDB_ROOT_PASSWORD: root_123456
      MONGO_INITDB_DATABASE: symphony

  redis:
    image: redis
    ports:
      - "6380:6379"

  backend:
    container_name: backend
    build: ./backend
    working_dir: /app/backend
    volumes: 
      - ./backend:/app/backend
    depends_on: ["mongo", "redis"]
    environment: 
      POSTGRES_USER: tandat
      POSTGRES_PASSWORD: root_123456
      POSTGRES_DB: symphony
      POSTGRES_HOST: postgres
      MONGO_USER: tandat
      MONGO_PASSWORD: root_123456
      MONGO_DB: symphony
      REDIS_URI: redis://redis:6380
    command: yarn dev
    ports:
      - 5000:5000

  frontend:
    container_name: frontend
    build: ./frontend
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
